export const COPY = {
  brand: {
    name: "Tiwa Gold",
    tagline: "XAU/USD trading intelligence, built for the phone in your pocket.",
  },
  auth: {
    login: {
      title: "Welcome back",
      subtitle: "Sign in to continue your edge on gold.",
      emailLabel: "Email",
      emailPlaceholder: "you@tiwagold.app",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      submit: "Sign in",
      submitting: "Signing in…",
      switchToSignup: "New here? Create an account",
      error: "We couldn't sign you in. Check your email and password.",
    },
    signup: {
      title: "Create your account",
      subtitle: "Three steps to your first setup review.",
      submit: "Continue",
    },
    gate: {
      title: "Finish onboarding",
      subtitle: "Your profile isn't complete yet.",
      resume: "Resume onboarding",
    },
  },
  onboarding: {
    steps: [
      {
        id: "welcome",
        eyebrow: "Step 1 of 3",
        title: "Built for the gold trader's edge",
        body: "Tiwa Gold surfaces only XAU/USD setups that pass our conservative, aggressive, and sniper engines — never noise.",
        primary: "Continue",
      },
      {
        id: "risk",
        eyebrow: "Step 2 of 3",
        title: "Set your risk profile",
        body: "Tell us how you size. We'll block setups that breach your plan before they hit your broker.",
        primary: "Continue",
      },
      {
        id: "broker",
        eyebrow: "Step 3 of 3",
        title: "Connect a broker",
        body: "Start with a paper account — live-sim is identical to production. Swap to live when you're ready.",
        primary: "Enter Tiwa Gold",
      },
    ],
    riskOptions: [
      { id: "conservative", label: "Conservative", hint: "0.25–0.5% per trade" },
      { id: "balanced", label: "Balanced", hint: "0.5–1.0% per trade" },
      { id: "aggressive", label: "Aggressive", hint: "1.0–2.0% per trade" },
    ],
  },
  tabs: {
    trades: "Trades",
    analytics: "Analytics",
    copilot: "Copilot",
    settings: "Settings",
  },
  tradeFeed: {
    title: "Live setups",
    subtitle: "XAU/USD · filtered by your engines",
    loading: "Scanning the tape…",
    empty: {
      title: "No setups right now",
      body: "The engines are watching. We'll notify you when a clean setup prints.",
    },
    error: {
      title: "Couldn't load setups",
      body: "Check your connection and try again.",
      retry: "Retry",
    },
    filter: {
      all: "All",
      active: "Open",
      pending: "Pending",
      closed: "Closed",
    },
  },
  macroRadar: {
    title: "Macro radar",
    subtitle: "High-impact events on the tape",
    loading: "Syncing macro calendar…",
    empty: {
      title: "Calendar is quiet",
      body: "No material gold catalysts inside the next window.",
    },
    error: {
      title: "Radar offline",
      body: "We couldn't reach the macro feed.",
      retry: "Retry",
    },
    bias: {
      bullish: "Bull bias",
      bearish: "Bear bias",
      neutral: "Two-way",
    },
    impact: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    when: {
      now: "Live",
      past: "Recent",
      future: "Upcoming",
    },
  },
  tradeDetail: {
    loading: "Loading setup…",
    sections: {
      thesis: "Thesis",
      logic: "Logic",
      levels: "Levels",
      context: "Context",
      confluence: "Confluence",
      timeline: "Timeline",
      autopsy: "Autopsy",
      visualizer: "Price map",
      risk: "Risk",
      execution: "Execution",
    },
    sectionCaptions: {
      context: "Regime + structure",
      logic: "Why this setup exists",
      risk: "Sizing + reward geometry",
      execution: "Broker routing + fill",
      autopsy: "Post-trade breakdown",
    },
    autopsy: {
      outcome: {
        win: "Win",
        loss: "Loss",
        breakeven: "Breakeven",
      },
      stats: {
        exit: "Exit",
        pnl: "PnL",
        duration: "Duration",
      },
      lessons: "Lessons",
      empty: "No post-trade notes yet.",
    },
    fields: {
      entry: "Entry",
      stop: "Stop",
      tp1: "TP1",
      tp2: "TP2",
      rr: "R:R",
      score: "Score",
      session: "Session",
      engine: "Engine",
      mode: "Mode",
      status: "Status",
      expiresAt: "Expires",
      htfTrend: "HTF trend",
      ltfStructure: "LTF structure",
      atr14: "ATR (14)",
      spread: "Spread",
      currentPrice: "Last price",
      strategyTag: "Strategy",
      setupType: "Setup",
      stopDistance: "Stop distance",
      tp1Distance: "TP1 distance",
      tp2Distance: "TP2 distance",
      brokerTicket: "Broker ticket",
      actualEntry: "Filled at",
      phase: "Phase",
      filledAt: "Filled",
      slippage: "Slippage",
      attempt: "Attempt",
      lastCheckedAt: "Last checked",
    },
    executionPhase: {
      queued: "Queued",
      routing: "Routing",
      pending_fill: "Pending fill",
      filled: "Filled",
      rejected: "Rejected",
      cancelled: "Cancelled",
    },
    lock: {
      contextAwaiting: "Waiting for data",
      executionPending: "Awaiting approval",
      executionClosed: "Already closed",
    },
    placeholder: {
      noValue: "—",
      noTicket: "Not assigned",
      noFill: "Not filled yet",
    },
    actions: {
      approve: "Approve setup",
      cancel: "Cancel setup",
      annotate: "Add note",
    },
    slideToExecute: {
      approveIdle: "Slide to approve",
      executeIdle: "Slide to execute",
      pending: "Routing to broker…",
      success: "Done",
      locked: "Locked",
      error: "Try again",
      reducedMotionApprove: "Tap to approve",
      reducedMotionExecute: "Tap to execute",
      hint: "Hold and slide",
      intentError: {
        missing_intent: "Couldn't verify this action. Please try again.",
        invalid_intent: "Authorization expired. Please try again.",
        backend_unavailable: "Broker confirmation offline. Try again shortly.",
        network: "Connection issue. Check your network and retry.",
      },
    },
    empty: {
      title: "Setup unavailable",
      body: "This trade may have expired or been cancelled.",
      back: "Back to feed",
      timeline: "No events logged yet.",
    },
    error: {
      title: "Couldn't load setup",
      body: "Check your connection and try again.",
      retry: "Retry",
    },
  },
  analytics: {
    title: "Performance",
    subtitle: "Last 30 days",
    kpis: {
      totalTrades: "Trades",
      activeTrades: "Active",
      closedTrades: "Closed",
      winRate: "Win rate",
      avgR: "Avg R",
      totalR: "Total R",
      bestTrade: "Best trade",
      worstTrade: "Worst trade",
      expectancy: "Expectancy",
      streak: "Streak",
    },
    sections: {
      equity: "Equity curve",
      byEngine: "By engine",
      bySession: "By session",
      byMode: "By mode",
    },
    empty: {
      title: "Not enough history yet",
      body: "Take a few setups and your analytics will populate here.",
    },
  },
  copilot: {
    title: "Copilot",
    subtitle: "Focused XAU/USD assistant",
    placeholder: "Ask about a setup, session, or risk…",
    send: "Send",
    sending: "Thinking…",
    typing: "Copilot is thinking…",
    empty: {
      title: "What's on your mind?",
      body: "Pick a prompt or type your own — Copilot references your live setups.",
    },
    error: {
      title: "Copilot is unreachable",
      body: "We'll retry when you send your next message.",
      retry: "Retry",
    },
    disclaimer:
      "Copilot provides decision support, not financial advice. You own every trade.",
  },
  settings: {
    title: "Settings",
    sections: {
      profile: "Profile",
      broker: "Broker",
      risk: "Risk",
      notifications: "Notifications",
      app: "App",
      legal: "Legal",
    },
    broker: {
      connected: "Connected",
      disconnected: "Not connected",
      connect: "Connect broker",
      disconnect: "Disconnect",
      lastSynced: "Last synced",
    },
    notifications: {
      signalAlerts: "Signal alerts",
      riskBlocks: "Risk block alerts",
      dailyRecap: "Daily recap",
      macroRadar: "Macro radar",
    },
    legal: {
      terms: "Terms of service",
      privacy: "Privacy policy",
      disclaimer: "Trading disclaimer",
    },
    actions: {
      signOut: "Sign out",
    },
  },
  riskBlock: {
    dailyLoss: "Daily loss limit hit — no new setups today.",
    duplicate: "Duplicate setup suppressed by dedupe window.",
    sessionMismatch: "Setup rejected: outside your enabled sessions.",
    lowScore: "Setup rejected: score below your minimum.",
  },
  common: {
    cancel: "Cancel",
    confirm: "Confirm",
    done: "Done",
    retry: "Retry",
    close: "Close",
    comingSoon: "Coming soon",
  },
} as const;

export type AppCopy = typeof COPY;
